version: "3"

services:
  web:
    container_name: test_service
    build: .
    command: python mange.py test & python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
