name: ci-cd-pipeline
on:
  push:
    branches:
      - main
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: docker-build & start
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
